title = "J2016+4231"

[Name]
value = "J2016+4231"
ref = "plots/J2016+4231.fft.png" #hyperlink to discovery plot

[Period]
value = 1243.77 #ms
ref = ""

[DM]
value = 222 #pc/cc
ref = "" 

[SinglePulse]
value = "None"
ref = "" #if true, put hyperlink here

[Discovery]
value = "UWM"
ref = ""

[Search]
value = 'PEASOUP'
ref = ""

#References go here
