title = "J2035+3538"

[Name]
value = "J2035+3538"
ref = "plots/J2035+3538.peasoup.png" #hyperlink to discovery plot

[Period]
value = 480. #ms
ref = ""

[DM]
value = 224 #pc/cc
ref = ""

[SinglePulse]
value = "None"
ref = "" #if true, put hyperlink here

[Discovery]
value = "UWM"
ref = ""

[Search]
value = 'PEASOUP'
ref = ""

#References go here
